/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.coffeemanager.view;

import com.coffeemanager.model.ChiTietHoaDon;
import com.coffeemanager.model.Connect;
import com.coffeemanager.model.DanhSachHoaDon;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Yuu
 */
public class FormDanhSachHoaDon extends javax.swing.JFrame {

    /**
     * Creates new form DanhSachHoaDon
     */
    public FormDanhSachHoaDon() {
        initComponents();
        txt_doanhThu.setEditable(false);
        loadSanPhamVaoBang(); // Load danh sách hóa đơn
        setLocationRelativeTo(null); // Đặt form ở giữa màn hình
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DSHoaDon = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_doanhThu = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn_xoaAll = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_ChiTietHD = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_DSHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Ngày Tạo", "Giờ Tạo", "Thành Tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_DSHoaDon);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Doanh Thu");

        txt_doanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_doanhThuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txt_doanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_doanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btn_xoaAll.setText("Xóa All");
        btn_xoaAll.setPreferredSize(new java.awt.Dimension(98, 23));
        btn_xoaAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaAllActionPerformed(evt);
            }
        });

        btn_Xoa.setText("Xóa");
        btn_Xoa.setPreferredSize(new java.awt.Dimension(98, 23));
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_ChiTietHD.setText("Xem Chi Tiết");
        btn_ChiTietHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChiTietHDActionPerformed(evt);
            }
        });

        jLabel3.setText("Quản Lý");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btn_ChiTietHD)
                        .addGap(31, 31, 31)
                        .addComponent(btn_xoaAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_xoaAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ChiTietHD))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("DANH SÁCH HÓA ĐƠN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadSanPhamVaoBang() {
        Connect sq = new Connect();
        DefaultTableModel tblModel = (DefaultTableModel) tbl_DSHoaDon.getModel();
        tblModel.setRowCount(0);
        List<DanhSachHoaDon> userList = sq.getAllHoaDon();
        for (DanhSachHoaDon user : userList) {
            if (user != null) {
                tblModel.addRow(new Object[]{user.getMaHD(), user.getNgayTao(), user.getGioTao(), user.getTongTien()});
            }
        }
        updateDoanhThu(); // Cập nhật doanh thu sau khi load
    }

    private void updateDoanhThu() {
        DefaultTableModel model = (DefaultTableModel) tbl_DSHoaDon.getModel();
        double total = 0.0;
        for (int i = 0; i < model.getRowCount(); i++) {
            total += (Double) model.getValueAt(i, 3); // Cột "Thành Tiền"
        }
        txt_doanhThu.setText(String.format("%,.2f VNĐ", total));
    }

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        int selectedRow = tbl_DSHoaDon.getSelectedRow();
        if (selectedRow >= 0) {
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                    "Bạn có chắc muốn xóa hóa đơn này?",
                    "Xác nhận xóa",
                    javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                DefaultTableModel model = (DefaultTableModel) tbl_DSHoaDon.getModel();
                int maHD = (Integer) model.getValueAt(selectedRow, 0);

                // Xóa trong cơ sở dữ liệu
                Connect sq = new Connect();
                try (Connection conn = sq.connectHoaDon(); java.sql.PreparedStatement pstmt1 = conn.prepareStatement("DELETE FROM ChiTietHoaDon WHERE maHD = ?"); java.sql.PreparedStatement pstmt2 = conn.prepareStatement("DELETE FROM DanhSachHoaDon WHERE maHD = ?")) {
                    conn.setAutoCommit(false);
                    pstmt1.setInt(1, maHD);
                    pstmt1.executeUpdate();
                    pstmt2.setInt(1, maHD);
                    pstmt2.executeUpdate();
                    conn.commit();

                    // Xóa khỏi bảng giao diện
                    model.removeRow(selectedRow);
                    updateDoanhThu();
                    javax.swing.JOptionPane.showMessageDialog(this, "Xóa hóa đơn thành công!");
                } catch (SQLException e) {
                    e.printStackTrace();
                    javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi xóa hóa đơn: " + e.getMessage());
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Vui lòng chọn một hóa đơn để xóa!",
                    "Lỗi",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_ChiTietHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChiTietHDActionPerformed
         int selectedRow = tbl_DSHoaDon.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, 
                "Vui lòng chọn một hóa đơn để xem chi tiết!", 
                "Lỗi", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Lấy mã hóa đơn từ dòng được chọn
        DefaultTableModel model = (DefaultTableModel) tbl_DSHoaDon.getModel();
        int maHD = (Integer) model.getValueAt(selectedRow, 0);

        // Lấy danh sách chi tiết hóa đơn
        Connect sq = new Connect();
        List<ChiTietHoaDon> chiTietList = sq.getChiTietHoaDonByMaHD(maHD);

        // Tạo JDialog để hiển thị chi tiết
        JDialog dialog = new JDialog(this, "Chi Tiết Hóa Đơn - Mã HD: " + maHD, true);
        dialog.setLayout(new BorderLayout());
        dialog.setSize(600, 400);
        dialog.setLocationRelativeTo(this); // Căn giữa dialog

        // Tạo JTable cho chi tiết hóa đơn (không có cột ID)
        DefaultTableModel chiTietModel = new DefaultTableModel(
            new Object[][]{},
            new String[]{"Tên Sản Phẩm", "Số Lượng", "Đơn Giá", "Tổng Tiền"}
        ) {
            Class[] types = new Class[]{
                String.class, Integer.class, Double.class, Double.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        JTable chiTietTable = new JTable(chiTietModel);
        JScrollPane scrollPane = new JScrollPane(chiTietTable);

        // Load dữ liệu chi tiết hóa đơn vào bảng
        for (ChiTietHoaDon cthd : chiTietList) {
            double tongTien = cthd.getSoLuong() * cthd.getDonGia();
            chiTietModel.addRow(new Object[]{
                cthd.getTenSanPham(),
                cthd.getSoLuong(),
                cthd.getDonGia(),
                tongTien
            });
        }

        // Tạo nút Đóng
        JButton btnDong = new JButton("Đóng");
        btnDong.addActionListener(e -> dialog.dispose());

        // Tạo panel chứa nút Đóng
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        buttonPanel.add(btnDong);

        // Thêm các thành phần vào dialog
        dialog.add(scrollPane, BorderLayout.CENTER);
        dialog.add(buttonPanel, BorderLayout.SOUTH);

        // Hiển thị dialog
        dialog.setVisible(true);
    }//GEN-LAST:event_btn_ChiTietHDActionPerformed

    private void btn_xoaAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaAllActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn xóa tất cả hóa đơn?",
                "Xác nhận xóa tất cả",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            DefaultTableModel model = (DefaultTableModel) tbl_DSHoaDon.getModel();
            model.setRowCount(0);
            updateDoanhThu();
            javax.swing.JOptionPane.showMessageDialog(this, "Xóa tất cả hóa đơn thành công!");

    }    }//GEN-LAST:event_btn_xoaAllActionPerformed

    private void txt_doanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_doanhThuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_doanhThuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhSachHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhSachHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhSachHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhSachHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDanhSachHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ChiTietHD;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_xoaAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_DSHoaDon;
    private javax.swing.JTextField txt_doanhThu;
    // End of variables declaration//GEN-END:variables
}
