package com.coffeemanager.view;

import com.coffeemanager.model.LichLamModel;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author Admin
 */
public class FormLichLam extends javax.swing.JFrame {

    public FormLichLam() {
        initComponents();
        loadLichLamVaoBang();
    }

    private Connection connect() throws SQLException {
        return DriverManager.getConnection("jdbc:sqlite:CoffeeManager.db");
    }

    private boolean isValidTimeRange(String input) {
        return input.matches("\\d{2}:\\d{2}\\s?-\\s?\\d{2}:\\d{2}");
    }

    private double calculateShiftHours(String shift) {
        String[] times = shift.replace("SA", "").replace("PM", "").trim().split(" - ");
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm");
        LocalTime start = LocalTime.parse(times[0].trim(), formatter);
        LocalTime end = LocalTime.parse(times[1].trim(), formatter);
        return ChronoUnit.MINUTES.between(start, end) / 60.0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lb_DanhMuc = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_themLichLam = new javax.swing.JButton();
        btn_suaLichLam = new javax.swing.JButton();
        btn_xoaLichLam = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_DangKyLichLam = new javax.swing.JTable();
        cbboxThu = new javax.swing.JComboBox<>();
        cbboxCaLam = new javax.swing.JComboBox<>();
        btn_TinhTongGio = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_DanhMuc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb_DanhMuc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_DanhMuc.setText("Danh mục :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lịch làm", "Bảng lương", "Ứng lương ", "Bảng phạt" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lb_DanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_DanhMuc)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đăng Ký Lịch làm");

        jLabel2.setText("Thứ làm");

        btn_themLichLam.setText("Thêm");
        btn_themLichLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themLichLamActionPerformed(evt);
            }
        });

        btn_suaLichLam.setText("Sửa");
        btn_suaLichLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaLichLamActionPerformed(evt);
            }
        });

        btn_xoaLichLam.setText("Xóa");
        btn_xoaLichLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaLichLamActionPerformed(evt);
            }
        });

        jLabel3.setText("Giờ làm");

        tbl_DangKyLichLam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Thứ ", "Ca làm", "Số giờ làm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_DangKyLichLam);

        cbboxThu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thứ Hai", "Thứ Ba", "Thứ Tư", "Thứ Năm", "Thứ Sáu", "Thứ Bảy", "Chủ Nhật" }));

        cbboxCaLam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00 - 12:00 SA", "13:00 - 18:00 PM", "18:00 - 23:00 PM" }));

        btn_TinhTongGio.setText("Tính Tổng Giờ");
        btn_TinhTongGio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TinhTongGioActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Mã NV:");

        jMenu1.setText("Trang chủ");

        jMenuItem1.setText("Quay lại Trang chủ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(cbboxThu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbboxCaLam, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(btn_themLichLam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_suaLichLam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_xoaLichLam)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_TinhTongGio))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1)
                                .addGap(390, 390, 390)))))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_themLichLam)
                    .addComponent(btn_suaLichLam)
                    .addComponent(btn_xoaLichLam)
                    .addComponent(cbboxThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbboxCaLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TinhTongGio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadLichLamVaoBang() {
        DefaultTableModel model = (DefaultTableModel) tbl_DangKyLichLam.getModel();
        model.setRowCount(0);
        try (Connection conn = connect(); Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery("SELECT * FROM LichLam")) {
            while (rs.next()) {
                String maNV = rs.getString("maNV");
                String thu = rs.getString("thu");
                String ca = rs.getString("ca");
                double soGio = rs.getDouble("soGio");
                model.addRow(new Object[]{maNV, thu, ca, soGio});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu: " + e.getMessage());
        }
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn_themLichLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themLichLamActionPerformed
        String maNV = jTextField1.getText().trim();
        String thu = (String) cbboxThu.getSelectedItem();
        String caLam = (String) cbboxCaLam.getSelectedItem();
        double hours = calculateShiftHours(caLam);

        String sql = "INSERT INTO LichLam (maNV, thu, ca, soGio) VALUES (?, ?, ?, ?)";
        try (Connection conn = connect(); PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, maNV);
            pstmt.setString(2, thu);
            pstmt.setString(3, caLam);
            pstmt.setDouble(4, hours);
            pstmt.executeUpdate();
            loadLichLamVaoBang();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_themLichLamActionPerformed

    private void btn_suaLichLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaLichLamActionPerformed
        int selectedRow = tbl_DangKyLichLam.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        String maNV = (String) tbl_DangKyLichLam.getValueAt(selectedRow, 0);
        String thu = (String) cbboxThu.getSelectedItem();
        String caLam = (String) cbboxCaLam.getSelectedItem();
        double hours = calculateShiftHours(caLam);

        String sql = "UPDATE LichLam SET thu = ?, ca = ?, soGio = ? WHERE maNV = ? AND thu = ? AND ca = ?";
        try (Connection conn = connect(); PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, thu);
            pstmt.setString(2, caLam);
            pstmt.setDouble(3, hours);
            pstmt.setString(4, maNV);
            pstmt.setString(5, (String) tbl_DangKyLichLam.getValueAt(selectedRow, 1));
            pstmt.setString(6, (String) tbl_DangKyLichLam.getValueAt(selectedRow, 2));
            pstmt.executeUpdate();
            loadLichLamVaoBang();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi sửa: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_suaLichLamActionPerformed

    private void btn_xoaLichLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaLichLamActionPerformed
        int selectedRow = tbl_DangKyLichLam.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }

        String maNV = (String) tbl_DangKyLichLam.getValueAt(selectedRow, 0);
        String thu = (String) tbl_DangKyLichLam.getValueAt(selectedRow, 1);
        String ca = (String) tbl_DangKyLichLam.getValueAt(selectedRow, 2);

        String sql = "DELETE FROM LichLam WHERE maNV = ? AND thu = ? AND ca = ?";
        try (Connection conn = connect(); PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, maNV);
            pstmt.setString(2, thu);
            pstmt.setString(3, ca);
            pstmt.executeUpdate();
            loadLichLamVaoBang();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi xóa: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_xoaLichLamActionPerformed

    private void btn_TinhTongGioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TinhTongGioActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl_DangKyLichLam.getModel();
        Map<String, Double> tongGio = new HashMap<>();
        Map<String, Integer> tongCa = new HashMap<>();

        for (int i = 0; i < model.getRowCount(); i++) {
            String ma = (String) model.getValueAt(i, 0);
            double gio = ((Number) model.getValueAt(i, 3)).doubleValue();
            tongGio.put(ma, tongGio.getOrDefault(ma, 0.0) + gio);
            tongCa.put(ma, tongCa.getOrDefault(ma, 0) + 1);
        }

        StringBuilder sb = new StringBuilder();
        for (String ma : tongGio.keySet()) {
            sb.append(ma).append(": ").append(tongCa.get(ma)).append(" ca, ")
                    .append(String.format("%.2f", tongGio.get(ma))).append(" giờ\n");
        }

        JOptionPane.showMessageDialog(this, sb.toString(), "Tổng giờ làm", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_TinhTongGioActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLichLam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLichLam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLichLam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLichLam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLichLam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_TinhTongGio;
    private javax.swing.JButton btn_suaLichLam;
    private javax.swing.JButton btn_themLichLam;
    private javax.swing.JButton btn_xoaLichLam;
    private javax.swing.JComboBox<String> cbboxCaLam;
    private javax.swing.JComboBox<String> cbboxThu;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lb_DanhMuc;
    private javax.swing.JTable tbl_DangKyLichLam;
    // End of variables declaration//GEN-END:variables

}
