/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.coffeemanager.view;

/**
 *
 * @author Yuu
 */
public class FormNhanVienHome extends javax.swing.JFrame {

    private String chucVu;

    /**
     * Creates new form FormQuanLyMenu
     */
    public FormNhanVienHome(String chucVu) {
        this.chucVu = chucVu;
        initComponents();

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_TaoHoaDon = new javax.swing.JButton();
        btn_DanhSachHoaDon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("APPLICATION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, 20));

        jLabel3.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jLabel3.setText("COFFEE MANAGER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("GRUOP 3");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        btn_TaoHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_TaoHoaDon.setText("Tạo Hóa Đơn");
        btn_TaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaoHoaDonActionPerformed(evt);
            }
        });
        getContentPane().add(btn_TaoHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 170, 40));

        btn_DanhSachHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_DanhSachHoaDon.setText("Danh Sách Hóa Đơn");
        btn_DanhSachHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DanhSachHoaDonActionPerformed(evt);
            }
        });
        getContentPane().add(btn_DanhSachHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/coffeemanager/image/37ba434e1ec765ddad8e5853b345479e.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaoHoaDonActionPerformed
        new FormHoaDon(chucVu).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_TaoHoaDonActionPerformed

    private void btn_DanhSachHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DanhSachHoaDonActionPerformed
        new FormDanhSachHoaDon(chucVu).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_DanhSachHoaDonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DanhSachHoaDon;
    private javax.swing.JButton btn_TaoHoaDon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
