/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.coffeemanager.view;

import com.coffeemanager.model.Connect;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import java.util.regex.Pattern;

/**
 *
 * @author Yuu
 */
public class FormDangKyTaiKhoan extends javax.swing.JFrame {

    // Regular expression for email validation (must end with @gmail.com)
    private static final Pattern EMAIL_PATTERN = Pattern.compile(
            "^[A-Za-z0-9+_.-]+@gmail\\.com$"
    );

    /**
     * Creates new form FormDangKyTaiKhoan
     */
    public FormDangKyTaiKhoan() {
        initComponents();
        setLocationRelativeTo(null); // Đặt form ở giữa màn hình
        // Group radio buttons
        ButtonGroup genderGroup = new ButtonGroup();
        genderGroup.add(rdobtn_Nam);
        genderGroup.add(rdobtn_Nu);
        genderGroup.add(rdobtn_Khac);
    }

    // Hàm tạo mã nhân viên tự động
    private String generateMaNV(String chucVu) {
        String prefix = chucVu.equals("Nhân Viên") ? "NV" : "QL";
        int count = 0;
        String sql = "SELECT COUNT(*) FROM Employees WHERE maNV LIKE ?";

        try (Connection conn = new Connect().connect(); PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, prefix + "%");
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                count = rs.getInt(1) + 1; // Tăng số thứ tự lên 1
            }
            rs.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return String.format("%s%03d", prefix, count); // Định dạng: NV001, QL001, ...
    }

    // Hàm kiểm tra trùng lặp tài khoản
    private boolean isTaiKhoanExists(String taiKhoan) {
        String sql = "SELECT COUNT(*) FROM Employees WHERE taiKhoan = ?";
        try (Connection conn = new Connect().connect(); PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, taiKhoan);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                return rs.getInt(1) > 0;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }

    // Hàm kiểm tra số điện thoại (10 chữ số)
    private boolean isValidPhoneNumber(String soDienThoai) {
        return soDienThoai.matches("\\d{10}");
    }

    // Hàm kiểm tra định dạng email
    private boolean isValidEmail(String email) {
        return EMAIL_PATTERN.matcher(email).matches();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        txt_SoDienThoai = new javax.swing.JTextField();
        txt_TenDangKi = new javax.swing.JTextField();
        txt_DiaChi = new javax.swing.JTextField();
        txt_MatKhau = new javax.swing.JTextField();
        txt_NhapLaiMatKhau = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lb_TenDangKi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbx_chucVu = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_FullName = new javax.swing.JTextField();
        rdobtn_Nu = new javax.swing.JRadioButton();
        rdobtn_Nam = new javax.swing.JRadioButton();
        rdobtn_Khac = new javax.swing.JRadioButton();
        txt_maNV = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_dangKy = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_SoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SoDienThoaiActionPerformed(evt);
            }
        });
        getContentPane().add(txt_SoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 330, -1));

        txt_TenDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenDangKiActionPerformed(evt);
            }
        });
        getContentPane().add(txt_TenDangKi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 330, -1));

        txt_DiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DiaChiActionPerformed(evt);
            }
        });
        getContentPane().add(txt_DiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 330, -1));

        txt_MatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MatKhauActionPerformed(evt);
            }
        });
        getContentPane().add(txt_MatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 330, -1));

        txt_NhapLaiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NhapLaiMatKhauActionPerformed(evt);
            }
        });
        getContentPane().add(txt_NhapLaiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 330, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Số điện thoại:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 95, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Email: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 51, 30));

        lb_TenDangKi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_TenDangKi.setText("Tài khoản: ");
        getContentPane().add(lb_TenDangKi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 95, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Mật khẩu:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Xác nhận mật khẩu:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 130, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Chức vụ: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        cbx_chucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân Viên", "Quản Lý" }));
        cbx_chucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_chucVuActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_chucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 330, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Họ tên nhân viên:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Giới tính: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        txt_FullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FullNameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_FullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 330, -1));

        rdobtn_Nu.setText("Nữ");
        getContentPane().add(rdobtn_Nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        rdobtn_Nam.setText("Nam");
        getContentPane().add(rdobtn_Nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        rdobtn_Khac.setText("Khác");
        getContentPane().add(rdobtn_Khac, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        txt_maNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maNVActionPerformed(evt);
            }
        });
        getContentPane().add(txt_maNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 330, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Mã Nhân Viên: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        btn_dangKy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_dangKy.setText("Đăng Ký");
        btn_dangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangKyActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 343, 130, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("ĐĂNG KÝ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 90, -1));

        jMenu1.setText("Menu");

        jMenuItem1.setText("Quay lại Trang chủ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Đăng nhập");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new FormTrangChu().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void cbx_chucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_chucVuActionPerformed
        String selectedChucVu = (String) cbx_chucVu.getSelectedItem();
        String maNV = generateMaNV(selectedChucVu);
        txt_maNV.setText(maNV);
        txt_TenDangKi.setText(maNV);
        // Lấy phần số của mã nhân viên (bỏ tiền tố NV hoặc QL)
        String numericPart = maNV.replaceAll("[^0-9]", "");
        txt_MatKhau.setText(numericPart);
        txt_NhapLaiMatKhau.setText(numericPart);
    }//GEN-LAST:event_cbx_chucVuActionPerformed

    private void btn_dangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangKyActionPerformed
        // Lấy dữ liệu từ các trường nhập liệu
        String maNV = txt_maNV.getText().trim();
        String fullName = txt_FullName.getText().trim();
        String sex = rdobtn_Nam.isSelected() ? "Nam" : rdobtn_Nu.isSelected() ? "Nữ" : "Khác";
        String chucVu = (String) cbx_chucVu.getSelectedItem();
        String taiKhoan = txt_TenDangKi.getText().trim();
        String matKhau = txt_MatKhau.getText().trim();
        String nhapLaiMatKhau = txt_NhapLaiMatKhau.getText().trim();
        String soDienThoai = txt_SoDienThoai.getText().trim();
        String email = txt_DiaChi.getText().trim();

        // Kiểm tra chức vụ hợp lệ
        if (chucVu == null || chucVu.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn chức vụ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Kiểm tra các trường bắt buộc
        if (fullName.isEmpty() || sex.isEmpty() || taiKhoan.isEmpty() || matKhau.isEmpty() || soDienThoai.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Kiểm tra số điện thoại
        if (!isValidPhoneNumber(soDienThoai)) {
            JOptionPane.showMessageDialog(this, "Số điện thoại phải gồm đúng 10 chữ số!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Kiểm tra định dạng email
        if (!isValidEmail(email)) {
            JOptionPane.showMessageDialog(this, "Email phải có định dạng ...@gmail.com!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Kiểm tra mật khẩu
        if (!matKhau.equals(nhapLaiMatKhau)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu và xác nhận mật khẩu không khớp!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Kiểm tra trùng lặp tài khoản
        if (isTaiKhoanExists(taiKhoan)) {
            JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Gọi hàm addEmployee từ class Connect
        Connect connect = new Connect();
        boolean success = connect.addEmployee(maNV, fullName, sex, chucVu, taiKhoan, matKhau, soDienThoai, email);

        // Hiển thị thông báo kết quả
        if (success) {
            JOptionPane.showMessageDialog(this, "Đăng ký tài khoản thành công! Mã nhân viên: " + maNV, "Thành công", JOptionPane.INFORMATION_MESSAGE);
            // Xóa các trường sau khi đăng ký thành công
            txt_maNV.setText("");
            txt_FullName.setText("");
            rdobtn_Nam.setSelected(false);
            rdobtn_Nu.setSelected(false);
            rdobtn_Khac.setSelected(false);
            txt_TenDangKi.setText("");
            txt_MatKhau.setText("");
            txt_NhapLaiMatKhau.setText("");
            txt_SoDienThoai.setText("");
            txt_DiaChi.setText("");
            cbx_chucVu.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(this, "Đăng ký tài khoản thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_dangKyActionPerformed

    private void txt_FullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FullNameActionPerformed
        btn_dangKyActionPerformed(evt);
    }//GEN-LAST:event_txt_FullNameActionPerformed

    private void txt_maNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maNVActionPerformed
        btn_dangKyActionPerformed(evt);
    }//GEN-LAST:event_txt_maNVActionPerformed

    private void txt_DiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DiaChiActionPerformed
        btn_dangKyActionPerformed(evt);
    }//GEN-LAST:event_txt_DiaChiActionPerformed

    private void txt_SoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SoDienThoaiActionPerformed
        btn_dangKyActionPerformed(evt);
    }//GEN-LAST:event_txt_SoDienThoaiActionPerformed

    private void txt_NhapLaiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NhapLaiMatKhauActionPerformed
        btn_dangKyActionPerformed(evt);
    }//GEN-LAST:event_txt_NhapLaiMatKhauActionPerformed

    private void txt_MatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MatKhauActionPerformed
        btn_dangKyActionPerformed(evt);
    }//GEN-LAST:event_txt_MatKhauActionPerformed

    private void txt_TenDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenDangKiActionPerformed
        btn_dangKyActionPerformed(evt);
    }//GEN-LAST:event_txt_TenDangKiActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new FormDangNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDangKyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDangKyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDangKyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDangKyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDangKyTaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangKy;
    private javax.swing.JComboBox<String> cbx_chucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lb_TenDangKi;
    private javax.swing.JRadioButton rdobtn_Khac;
    private javax.swing.JRadioButton rdobtn_Nam;
    private javax.swing.JRadioButton rdobtn_Nu;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_FullName;
    private javax.swing.JTextField txt_MatKhau;
    private javax.swing.JTextField txt_NhapLaiMatKhau;
    private javax.swing.JTextField txt_SoDienThoai;
    private javax.swing.JTextField txt_TenDangKi;
    private javax.swing.JTextField txt_maNV;
    // End of variables declaration//GEN-END:variables
}
